source ~/.config/nvim/plugins.lua
source ~/.config/nvim/plugin_configs/bufferline.lua
source ~/.config/nvim/plugin_configs/indent-blankline.lua
source ~/.config/nvim/plugin_configs/nvim-tree.lua
source ~/.config/nvim/plugin_configs/telescope.lua
source ~/.config/nvim/plugin_configs/nvim-cmp.lua
source ~/.config/nvim/plugin_configs/lsp.lua
source ~/.config/nvim/plugin_configs/treesitter.lua
source ~/.config/nvim/plugin_configs/lualine.lua
source ~/.config/nvim/plugin_configs/fidget.lua
source ~/.config/nvim/plugin_configs/spectre.lua
source ~/.config/nvim/plugin_configs/nvim-scrollbar.lua
source ~/.config/nvim/plugin_configs/nvim-hlslens.lua
source ~/.config/nvim/general_config.vim
source ~/.config/nvim/key_mappings/general.lua
